### ISSUE TITLE
Jumping and or Stuttering recordings

### ISSUE THREAD

**Issue by forsomefun2** [jrudess/streamdvr#125]
How are people still using the old sites that are no longer directly supported?

I want to switch to streamlink because ffmgeg is getting to be very jumpy in recordings depending on site. 

edit: I am also notice MFC stops recording after a few days now.

**Comment by forsomefun2** [comment]
How are people still using the old sites that are no longer directly supported?

I want to switch to streamlink because ffmgeg is getting to be very jumpy in recordings depending on site. 

edit: I am also notice MFC stops recording after a few days now.

**Comment by Hampster82** [comment]
You can just download an older version before the adult sites were pulled out.

The trouble is that if and when bugs happen, there's no good place to report them.
Like lately I've noticed at least some widescreen streams getting a lot of constant starting stopping starting stopping error where the stream is never recorded at all. Could be a bug in mfcauto, streamdvr script or who knows where else.

**Comment by forsomefun2** [comment]
@hamster82

Streamlink works much better in my case now.

Does your MFC crash as well.

**Comment by Hampster82** [comment]
Yeah, I actually switched to streamlink script to test it out, and it seems to be working perfectly. Took a look at some logs and it seems ffmpeg script is 404ing with the playlists or something, just can't find them.

But yeah, occasionally the recorder will just silently die on mfc and needs a restart, but that's an old problem.

**Comment by forsomefun2** [comment]
@Hampster82 

I think the newer form of MFC auto is supposed to last a few days without crashing. But the version I have 5.6.2 crashes at least once a day. 

I saw 5.7.1 or so floating around here, but I did not grab the link on time.

**Comment by Hampster82** [comment]
5.7.1 didn't really make a difference there as far as I've seen.

Also it seems like some widescreen models still have issues even after swapping to streamlink. Dug out an old mfc node fork with rtmp support and that works, at least for now.

**Comment by forsomefun2** [comment]
@Hampster82 

I found a few of these did you get the reverse proxy to work?

all of the ones I saw go to 9080

**Comment by Hampster82** [comment]
I have no idea what you mean by reverse proxy.

**Comment by forsomefun2** [comment]
That is okay 
I thought I needed it

There is an chrome extension to open multiple URL at once from a list. Notepad + + with notepad + + you can add something to everyline.

That way you can convert another list of UID to mfc-node format with the url in the instructions that come with the repositories.

**Comment by jrudess** [comment]
New version of MFCAuto (v5.11.2) uploaded here:  https://volafile.org/get/CAnjnyI9qHVat/MFCAuto_v5.11.2.tar.gz

Should be available for 48 hours.  Please post if this seems to help MFC connection stability at all.

**Comment by jrudess** [comment]
Also, mfc.js works just fine with the latest versions, so there's no need to use an old version of streamdvr.  

The only change is that the mfc plugin isn't a part of this repo.  You can just copy mfc.js to your yml config directory, and use an mfc.yml similar to this:

```
name: MFC
plugin: /home/.config/streamdvr/mfc
siteUrl: 'https://www.myfreecams.com/'
urlback: ''
enable: true
recorder: scripts/record_streamlink.sh
scanInterval: 300
mfcWebSocket: true
modernLogin: true
mfcautolog: false
streamers: []
```

**Comment by Hampster82** [comment]
That's not quite enough it seems, for a brand new install anyway. You need to either get the node_modules from an older install or older package-lock.json (and maybe package.json?) file so the necessary dependencies are installed when you run 'npm install'.

**Comment by Hampster82** [comment]
It seems like MFC changed something earlier today and completely broke everything. Enabling mfcautolog reveals all kinds of fun errors, almost looks like maybe their data structure changed or something.

**Comment by PurrSevere** [comment]
Was hoping it was just me. Does anyone have the removed script files up on a repo? That way we can move any issues to that repo. I can create one if not.

**Comment by nerdydude** [comment]
Yea. it was a data structure change. It has been changing a few times since I first saw the issue, but I was able to make a temporary fix by modifying a line in the processListData function in the Client.js file.

Not sure how long it will last but here is the vola room to get the file. 
[https://volafile.org/r/uxr08v14](room)

You just need to change line 685 in the client.js file from
``` js
schemaMap.push([key, prop2]);
```
to

```js
schemaMap.push(prop2);
```

**Comment by Hampster82** [comment]
Yup, that works. Thanks.

**Comment by jrudess** [comment]
Here's an official mfcauto release (v5.11.3) that has patches for the MFC change.  They are listed as a temporary workaround, and I expect a bigger release at some point.

https://volafile.org/get/CBbA8u43Pwzw0/MFCAuto_v5.11.3.tar.gz

@hampster82 Yes you are right about also needing to manually modify package.json to include MFCAuto since it is a dependency of the mfc plugin.

**Comment by forsomefun2** [comment]
Did CB make a change as well 
I can't get this program to work, but an alternative does/ 

I'm a little lost
install nvm
tried
11.6     11.11    9.4    and then 10.13.0 version of node non of those work. 
for some reason it is not starting the recording process. Or when models are online. 
Just that 50 Models are in my list.

**Comment by PurrSevere** [comment]
Working great here. At least my docker version is. I keep it updated when anything changes.
https://hub.docker.com/r/purrsevere/streamdvr-docker/

**Comment by deiot** [comment]
> Here's an official mfcauto release (v5.11.3) that has patches for the MFC change. They are listed as a temporary workaround, and I expect a bigger release at some point.
> 
> https://volafile.org/get/CBbA8u43Pwzw0/MFCAuto_v5.11.3.tar.gz

Hi jrudess, would you be so kind and reup the latest mfcauto? Thanks!

**Comment by jrudess** [comment]
Newest version of MFCAuto available here:
https://volafile.org/get/CDBA1fZPwfqgd/MFCAuto.v5.11.4.tar.gz

Link valid for 48 hours from the time of this post.

**Comment by Damianonymous** [comment]
@jrudess if it's not a problem, send me an update, I was late again ;)

**Comment by jrudess** [comment]
Reuploaded here: https://volafile.org/get/CD-UEIKCU8KgC/MFCAuto.v5.11.4.tar.gz

**Comment by Damianonymous** [comment]
As you know I'm green in this topic, I wonder if the hidden files should be in the repository? If so, how can I send them in the browser?

**Comment by jrudess** [comment]
I've created a tarball for the mfc plugin that allows it to work standalone without needing to modify streamdvr's package.json.   There is a readme file in the tarball explaining how to use it.   

Anyone can feel free to create a github repo and host the files in this tarball.   I've also just pushed some code cleanup commits that involved some variable name changes, so the old mfc plugin file floating around is no longer compatible with top-of-tree.

https://volafile.org/get/CEipAvtr8KNfE/streamdvr-mfc.tar.gz

**Comment by jrudess** [comment]
Fixed tarball originally posted (edited link).   If you see an npm warning about bad version, just delete the version line from package.json to fix.

**Comment by gammagramma** [comment]
Late to the party and with that comes missing both files. Can you re-up the streamdvr-mfc and newest mfc auto? Thanks!

**Comment by sstativa** [comment]
> Late to the party and with that comes missing both files. Can you re-up the streamdvr-mfc and newest mfc auto? Thanks!

https://github.com/Damianonymous/MFCAuto

**Comment by gammagramma** [comment]
Thank you @sstativa! And what about:

> I've created a tarball for the mfc plugin that allows it to work standalone without needing to modify streamdvr's package.json. There is a readme file in the tarball explaining how to use it.

Also, I would like to ask you a direct question. For a rtmpdump recording - especially with the patched version that you released, is there any workaround in a program like MFCD.exe that does not use it, but also potentially be Linux compatible?

Here I asked about this:

https://github.com/horacio9a/myfreecams-anonymous/issues/5

**Comment by gammagramma** [comment]
> I've created a tarball for the mfc plugin that allows it to work standalone without needing to modify streamdvr's package.json. There is a readme file in the tarball explaining how to use it.
> 
> Anyone can feel free to create a github repo and host the files in this tarball. I've also just pushed some code cleanup commits that involved some variable name changes, so the old mfc plugin file floating around is no longer compatible with top-of-tree.

@jrudess I think I installed MFCAuto properly with the custom package.json that implements its dependencies, however the line "cannot read property 'mfcautolog' undefined" among others still occurs, so I am guessing that I need the new mfc plugin, and that this is the same data structure problem, I also tried disabling mfcautolog in mfc.yml, but that did not work - I actually think it was disabled by default. Preferably a full standalone tarball re-up would be great, as the links are expired and no one asked since last time I questioned which was over a month from now and as @sstativa mentioned, the (probably still) newest version of MFCAuto can be found on a @Damianonymous repo, but not the new mfc.js file, except if I am dumb enough not realizing something.

**Comment by deiot** [comment]
> @jrudess I think I installed MFCAuto properly with the custom package.json that implements its dependencies, however the line "cannot read property 'mfcautolog' undefined" among others still occurs. [...]

Docker has an updated mfc plugin, and all the other dependencies. Pull with xxx tag.
`docker pull purrsevere/streamdvr-docker:xxx`
