### ISSUE TITLE
Stops working entirely after a period of time

### ISSUE THREAD

**Issue by e2489** [jrudess/streamdvr#141]
After updating, I've noticed that after a certain period of time, the program just stops working entirely. Doesn't pick up when streamers come online, doesn't record anything, etc.
I have to keep restarting it whenever possible just to make sure it's still working, and often times I'll get home at the end of the day to find that it hasn't recorded any of the streams for that day.

Never had this issue before updating to the Linux version, is there a specific reason that this is happening? I suppose I could force it to restart once an hour automatically, but that doesn't seem like a great option as it would split up recordings unecessarily. Any good way of fixing this?

**Comment by PurrSevere** [comment]
Same problem here. I recommend using commit 89962de or lower for the time being.

**Comment by e2489** [comment]
I'm using your xxx Docker version, pulled on May 4. Would that be lower? Says that commit is from 3 days ago, so I would assume so, but I'm still having this problem.

**Comment by PurrSevere** [comment]
That's strange. I've noticed a couple problems myself in the past couple of days with MFC only but everything seems to be back to normal. 

Try the latest build that I pushed a couple minutes ago. I switched to release-based builds instead of pushing a new build for every streamdvr commit. I may create a new tag for commit-based builds in the future but this was done for stability reasons.

**Comment by jrudess** [comment]
One of the changes I made while refactoring has removed the disconnect()/reconnect() pair for each cycle.  That older hack might be what has been preventing this problem for most people.   Will work on a patch to re-enable it as a config.yml option, and then you can see if re-enabling it helps.

Is this specific to mfc, or something you see for sites using the basic plugin?

**Comment by jrudess** [comment]
Please let me know if b86aaa114f83e4f6f79376e650f61094a75839a6 improves this.

**Comment by PurrSevere** [comment]
I just updated the docker image with new `dev` and `dev-xxx` tags that pull from streamdvr commits rather than releases. @e2489 give that a shot and see if it fixes your issues.

**Comment by Hampster82** [comment]
I also noticed the old problem resurface in a big way a few days ago, script could silently die somewhere between 10 and 30 minutes all of a sudden, and so I switched to an old mfc-node build that still works, at least temporarily.

It was never really truly fixed back in the day as far as I could see, the disconnect/reconnect hack might have mitigated the bug but I would still see it every now and then.

**Comment by e2489** [comment]
I pulled the latest dev-xxx version, I'll give that a try for a few days and see how it goes.

@ PurrSevere - Unrelated, but one thing I've noticed with this version is that password protected CB rooms are no longer being labeled as such and are spamming "cannot find URL" errors instead.

**Comment by jrudess** [comment]
The last error is my fault.  I forgot to post the latest version of mfc plugin somewhere.

Link valid for 48 hours: https://volafile.org/get/CS6Yr2V7KI3sa/mfc.js

**Comment by PurrSevere** [comment]
@e2489 The "Cannot find URL" error looks to be a youtube-dl problem. Testing with the streamlink m3u8 script doesn't show this error. Someone just needs to update the youtube-dl's chaturbate,py plugin to support that. 

The last error has been fixed in the latest dev-xxx image thanks to the updated mfc.js plugin above.

**Comment by e2489** [comment]
I can't even get streamlink to work with CB. All streamers show as offline and if I check the URL manually it says "error: No plugin can handle URL". Works fine with Twitch, etc.

Appreciate the update!

**Comment by e2489** [comment]
Also seeing this randomly now for MFC: "[ERROR[ Error: WebSocket is not open: readyState 2 (CLOSING)"

**Comment by jrudess** [comment]
The websocket error comes from an MFCAuto dependency, and is likely just due to network/mfc-server issues.   So the disconnect() and reconnect() on each loop should recover the connection.

**Comment by Hampster82** [comment]
FYI, this is definitely still happening every now and then. What I've done to "combat" it is to enable debug, so even when nothing is recording, the site disconnected/connected debug entry is posted at every loop and keeps the timestamp rolling. As soon as that stops, I know to restart the script. Obviously it doesn't help if I'm not around, don't notice it or whatever, but at least it makes it easy to tell if everything's working at a glance.

It is surprising that we haven't been able to narrow the underlying issue down.

**Comment by e2489** [comment]
It's gotten better for me after the update, I'm able to run it for several days without any issues now. Still getting random errors, but they don't seem to be causing problems.

**Comment by wearfears** [comment]
Can you please repost mfc plugin?
